### ISSUE TITLE
is the role ztp-install-packages using a template? 

### ISSUE THREAD

**Issue by ksator** [titom73/ansible-junos-ztp#26]
@titom73 hello, 
are we using the template https://github.com/titom73/ansible-junos-ztp/blob/master/roles/ztp-install-packages/templates/dhcp.j2 into the role https://github.com/titom73/ansible-junos-ztp/blob/master/roles/ztp-install-packages? I am asking this as I do not see the template module in the tasks executed with the role https://github.com/titom73/ansible-junos-ztp/blob/master/roles/ztp-install-packages/
MAny thanks in advance

**Comment by titom73** [comment]
Hi @ksator 

At that time, this template is not used. In futur version, it will be used to configure basic features of the DHCP server such as scopes and all generic options we can use in a DHCP service.

All templates are used in [`ztp-create-config`](https://github.com/titom73/ansible-junos-ztp/tree/master/roles/ztp-create-config) role where you can find related jinja2 files in [`templates` directory](https://github.com/titom73/ansible-junos-ztp/tree/master/roles/ztp-create-config/templates)

BR
